### ISSUE TITLE
Unable to run bubblejail. No such file or directory error.

### ISSUE THREAD

**Issue by ls0h** [igo95862/bubblejail#7]
Hi!

I am trying to use bubblejail on Ubuntu:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```
And cannot run a simple instance:
```
$ bubblejail list instances
test2
```
```
$ bubblejail run test2
b'bwrap: execvp /usr/lib/bubblejail/bubblejail-helper: No such file or directory\n'
```
bubblejail-helper exists:
```
$ ls -l /usr/lib/bubblejail/bubblejail-helper
-rwxr-xr-x 1 root root 224 фев  1 23:05 /usr/lib/bubblejail/bubblejail-helper
```
Nothing special, just xterm:
```
$ EDITOR=cat bubblejail edit test2
[common]
dbus_name = ""
executable_name = [ "/usr/bin/xterm",]
filter_disk_sync = false
share_local_time = true

[x11]

[network]

[pulse_audio]

[home_share]
home_paths = [ "Downloads",]

[direct_rendering]
enable_aco = true

[systray]

[joystick]

[notify]
```
Dry-run works:
```
$ bubblejail run --dry-run test2
Bwrap options:
--unshare-all --die-with-parent --as-pid-1 --new-session --uid 1000 --gid 1000 --proc /proc --dev /dev --unsetenv SHELL --unsetenv SESSION_MANAGER --unsetenv WINDOWID --unsetenv QT_ACCESSIBILITY --unsetenv QT_SCREEN_SCALE_FACTORS --unsetenv XDG_CONFIG_DIRS --unsetenv TERM_PROGRAM_VERSION --unsetenv GTK_IM_MODULE --unsetenv GTK2_MODULES --unsetenv QT4_IM_MODULE --unsetenv MANDATORY_PATH --unsetenv LC_ADDRESS --unsetenv LC_NAME --unsetenv SSH_AUTH_SOCK --unsetenv force_s3tc_enable --unsetenv XMODIFIERS --unsetenv DESKTOP_SESSION --unsetenv LC_MONETARY --unsetenv SSH_AGENT_PID --unsetenv GTK_RC_FILES --unsetenv XCURSOR_SIZE --unsetenv GPG_TTY --unsetenv GTK_MODULES --unsetenv XDG_SEAT --unsetenv PWD --unsetenv XDG_SESSION_DESKTOP --unsetenv LOGNAME --unsetenv XDG_SESSION_TYPE --unsetenv GPG_AGENT_INFO --unsetenv XAUTHORITY --unsetenv DESKTOP_STARTUP_ID --unsetenv WINDOWPATH --unsetenv GTK2_RC_FILES --unsetenv HOME --unsetenv USERNAME --unsetenv LC_PAPER --unsetenv LANG --unsetenv LS_COLORS --unsetenv XDG_CURRENT_DESKTOP --unsetenv XTERM_256_COLORS --unsetenv TERMINOLOGY --unsetenv CLUTTER_IM_MODULE --unsetenv KDE_SESSION_UID --unsetenv LESSCLOSE --unsetenv XDG_SESSION_CLASS --unsetenv TERM --unsetenv LC_IDENTIFICATION --unsetenv DEFAULTS_PATH --unsetenv LESSOPEN --unsetenv LIBVIRT_DEFAULT_URI --unsetenv USER --unsetenv KDE_SESSION_VERSION --unsetenv DISPLAY --unsetenv SHLVL --unsetenv LC_TELEPHONE --unsetenv QT_IM_MODULE --unsetenv LC_MEASUREMENT --unsetenv XDG_VTNR --unsetenv UBUNTU_MENUPROXY --unsetenv XDG_SESSION_ID --unsetenv XDG_RUNTIME_DIR --unsetenv LC_TIME --unsetenv QT_AUTO_SCREEN_SCALE_FACTOR --unsetenv XCURSOR_THEME --unsetenv XDG_DATA_DIRS --unsetenv KDE_FULL_SESSION --unsetenv PATH --unsetenv GDMSESSION --unsetenv DBUS_SESSION_BUS_ADDRESS --unsetenv KDE_APPLICATIONS_AS_SCOPE --unsetenv LC_NUMERIC --unsetenv TERM_PROGRAM --unsetenv _ --unsetenv OLDPWD --ro-bind /usr/include /usr/include --ro-bind /usr/bin /usr/bin --ro-bind /usr/lib /usr/lib --ro-bind /usr/lib32 /usr/lib32 --ro-bind /usr/share /usr/share --ro-bind /usr/src /usr/src --ro-bind /opt /opt --symlink /usr/lib /lib --symlink /usr/lib64 /lib64 --symlink /usr/bin /bin --symlink /usr/sbin /sbin --symlink /usr/lib /usr/lib64 --symlink /usr/bin /usr/sbin --ro-bind /etc/login.defs /etc/login.defs --ro-bind /etc/ld.so.cache /etc/ld.so.cache --ro-bind /etc/ld.so.conf /etc/ld.so.conf --ro-bind /etc/ld.so.conf.d /etc/ld.so.conf.d --dir /tmp --dir /var --dir /run/user/1000 --dir /usr/local --bind /home/lsh/.local/share/bubblejail/instances/test2/home /home/user --setenv USER user --setenv USERNAME user --setenv HOME /home/user --setenv PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/games --setenv XDG_RUNTIME_DIR /run/user/1000 --setenv LANG en_US.UTF-8 --file 6 /etc/passwd --file 7 /etc/group --file 8 /etc/nsswitch.conf --file 9 /etc/host.conf --file 10 /etc/hostname --file 11 /etc/hosts --file 12 /etc/machine-id --ro-bind /etc/localtime /etc/localtime --setenv XDG_SESSION_TYPE x11 --setenv XDG_SESSION_DESKTOP plasma --setenv XDG_CURRENT_DESKTOP KDE --setenv DESKTOP_SESSION plasma --setenv DISPLAY :1 --bind /tmp/.X11-unix/X1 /tmp/.X11-unix/X1 --ro-bind /run/user/1000/gdm/Xauthority /tmp/.Xauthority --ro-bind /etc/fonts /etc/fonts --setenv XAUTHORITY /tmp/.Xauthority --ro-bind /home/lsh/.config/kdeglobals /home/user/.config/kdeglobals --share-net --ro-bind /etc/resolv.conf /etc/resolv.conf --ro-bind /etc/ca-certificates /etc/ca-certificates --ro-bind /etc/ssl /etc/ssl --bind /run/user/1000/pulse/native /run/user/1000/pulse/native --symlink /usr/bin/true /usr/local/bin/pulseaudio --bind /home/lsh/Downloads /home/user/Downloads --symlink /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1 /sys/dev/char/226:1 --dev-bind /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 --symlink /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/renderD129 /sys/dev/char/226:129 --dev-bind /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 --symlink /sys/devices/pci0000:00/0000:00:02.0/drm/card0 /sys/dev/char/226:0 --dev-bind /sys/devices/pci0000:00/0000:00:02.0 /sys/devices/pci0000:00/0000:00:02.0 --symlink /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 /sys/dev/char/226:128 --dev-bind /sys/devices/pci0000:00/0000:00:02.0 /sys/devices/pci0000:00/0000:00:02.0 --dev-bind /dev/dri /dev/dri --setenv RADV_PERFTEST aco --dev-bind /dev/input/event4 /dev/input/event4 --symlink /dev/input/event4 /dev/input/by-path/pci-0000:00:14.0-usb-0:4:1.0-event-joystick --dev-bind /dev/input/js0 /dev/input/js0 --symlink /dev/input/js0 /dev/input/by-path/pci-0000:00:14.0-usb-0:4:1.0-joystick --symlink ../../devices/pci0000:00/0000:00:14.0/usb3/3-4/3-4:1.0/0003:1A34:0809.0001/input/input4/js0 /sys/class/input/js0 --dev-bind /sys/devices/pci0000:00/0000:00:14.0/usb3/3-4/3-4:1.0/0003:1A34:0809.0001 /sys/devices/pci0000:00/0000:00:14.0/usb3/3-4/3-4:1.0/0003:1A34:0809.0001 --symlink ../../devices/pci0000:00/0000:00:14.0/usb3/3-4/3-4:1.0/0003:1A34:0809.0001/input/input4/event4 /sys/class/input/event4 --dev-bind /sys/devices/pci0000:00/0000:00:14.0/usb3/3-4/3-4:1.0/0003:1A34:0809.0001 /sys/devices/pci0000:00/0000:00:14.0/usb3/3-4/3-4:1.0/0003:1A34:0809.0001 --setenv DBUS_SESSION_BUS_ADDRESS unix:path=/run/user/1000/bus --bind /run/user/1000/bubblejail/test2/dbus_session_proxy /run/user/1000/bus --bind /run/user/1000/bubblejail/test2/dbus_system_proxy /var/run/dbus/system_bus_socket --bind /run/user/1000/bubblejail/test2/dbus_system_proxy /run/dbus/system_bus_socket --bind /run/user/1000/bubblejail/test2/helper /run/bubblehelp --chdir /home/user
Bwrap args:
/usr/bin/bwrap --args 15 /usr/lib/bubblejail/bubblejail-helper /usr/bin/xterm
Dbus session args
xdg-dbus-proxy unix:path=/run/user/1000/bus /run/user/1000/bubblejail/test2/dbus_session_proxy --talk=org.kde.StatusNotifierWatcher --talk=org.freedesktop.Notifications --filter unix:path=/run/dbus/system_bus_socket /run/user/1000/bubblejail/test2/dbus_system_proxy --filter
```

**Comment by igo95862** [comment]
I think I know the issue.

Ubuntu has a different `/usr` structure than Arch.

I think I will install Ubuntu in to a VM to test.

Can you run `ls -l /usr` ? I want to see what symlinks there are.

**Comment by ls0h** [comment]
```
$ ls -l /usr
total 272
drwxr-xr-x   3 root root 135168 фев  1 23:05 bin
drwxr-xr-x   2 root root   4096 янв 24 01:23 games
drwxr-xr-x   5 root root   4096 окт 13 00:46 i686-w64-mingw32
drwxr-xr-x 146 root root  36864 янв 28 12:43 include
drwxr-xr-x 182 root root  20480 фев  1 23:05 lib
drwxr-xr-x   3 root root   4096 окт 26 13:05 lib32
drwxr-xr-x  21 root root  12288 янв 27 01:45 libexec
drwxr-xr-x  11 root root   4096 ноя 21  2018 local
drwxr-xr-x   2 root root  20480 янв 29 13:30 sbin
drwxr-xr-x 628 root root  20480 фев  1 22:00 share
drwxr-xr-x  13 root root   4096 янв 28 12:43 src
drwxr-xr-x   5 root root   4096 окт 13 00:47 x86_64-w64-mingw32
```
```
$ ls -l /
........
drwxr-xr-x   2 root root       4096 янв 28 12:43 bin
drwxr-xr-x   4 root root       4096 янв 28 12:46 boot
drwxr-xr-x   2 root root       4096 мая  7  2018 cdrom
drwxr-xr-x  23 root root       5420 фев  2 12:52 dev
drwxr-xr-x 217 root root      16384 фев  1 18:54 etc
drwxr-xr-x  10 root root       4096 янв 26 22:19 home
drwxr-xr-x  26 root root       4096 окт 26 13:10 lib
drwxr-xr-x   2 root root       4096 окт 26 13:03 lib32
drwxr-xr-x   2 root root       4096 окт 26 13:03 lib64
drwx------   2 root root      16384 ноя 22  2018 lost+found
drwxr-xr-x   3 root root       4096 ноя 21  2018 media
drwxr-xr-x   5 root root       4096 авг 12  2019 mnt
drwxr-xr-x  10 root root       4096 янв 11 21:27 opt
dr-xr-xr-x 449 root root          0 фев  2 12:51 proc
drwx------  18 root root       4096 янв 11 19:23 root
drwxr-xr-x  49 root root       1520 фев  2 12:57 run
drwxr-xr-x   2 root root      12288 янв 28 12:43 sbin
drwxr-xr-x  11 root root       4096 янв 24 01:25 snap
drwxr-xr-x   2 root root       4096 ноя 21  2018 srv
-rw-------   1 root root 2147483648 мая  7  2018 swapfile
dr-xr-xr-x  13 root root          0 фев  2 12:51 sys
drwxrwxrwt  22 root root        560 фев  2 13:01 tmp
drwxr-xr-x  14 root root       4096 окт 13 00:46 usr
drwxr-xr-x  15 root root       4096 апр 25  2020 var
```
Note: My OS has been updated from 18.04. Probably there are some differences in fresh 20.10 installation.

**Comment by igo95862** [comment]
Ok, I have tracked down the issue to the symlinks. Sec I will work on the patch.

**Comment by ls0h** [comment]
Looks like I found a solution too. It works with
```
yield ReadOnlyBind('/bin')
yield ReadOnlyBind('/sbin')
yield ReadOnlyBind('/lib')
yield ReadOnlyBind('/lib32')
yield ReadOnlyBind('/lib64')
```
added to BubblejailDefaults in services.py. I think it can be fixed by checking for symlinks in the root directory. 
P.S.: PATH environment variable should be fixed too to contain /bin and /sbin if they are not symlinks.

**Comment by igo95862** [comment]
I pushed the hotfix. It seems to work in my VM.

BTW not sure how you installed it on Ubuntu. Probably with `meson install`. If that is the case you will have a lot of untracked files by your package manager.

I will create a better meson configuration to handle installation.

**Comment by ls0h** [comment]
Now it works. Thank you very much!
I just copied the files to the target locations. Yes, I know that it is not a good idea, but there are not much files and they can be deleted by hands.
Could you make project structure more like one in destination directories, i.e. 'share' instead of 'data' and so on? This will make it easier to test.

**Comment by ls0h** [comment]
A little bug is still here. PATH does not contain /bin and /sbin dirs.

**Comment by igo95862** [comment]
> A little bug is still here. PATH does not contain /bin and /sbin dirs.

Should be fixed now.

> Could you make project structure more like one in destination directories, i.e. 'share' instead of 'data' and so on? This will make it easier to test.

Once I fix the build system the `sudo meson install` command would properly install all data regardless of distro or configuration. (`sudo ninja uninstall` would properly cleanup)

**Comment by ls0h** [comment]
>Should be fixed now.
Now everything is ok.

**Comment by ls0h** [comment]
>I pushed updated build system.

Looks like everything is ok and works from '/usr/local/' (default destination on my system).
